name: \U0001F6E0 Building an Application
description: Issues trying to compile or package your application.
labels: ["Area: App+Library Build", "needs-triage"]
assignees: ["jonathanpeppers", "dellis1972"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Please make sure to add as much detail as you can, preferably with a reproduction if possible. This will help us diagnose the issue faster and thus resolve it quicker.
  - type: checkboxes
    id: android-type
    attributes:
      label: Android application type
      description: In what type of Android application do you see this issue?
      options:
      - label: Classic Xamarin.Android (MonoAndroid11.0, MonoAndroid12.0, etc.)
      - label: Android for .NET (net6.0-android, etc.)
  - type: input
    id: platform-versions
    attributes:
      label: Affected platform version
      description: Please provide the version number of the platform you see this issue on.
      placeholder: E.g. VS 2022 17.0.1, VSMac 8.10, .NET 6.0.100, etc.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give us a detailed description of the issue that you're seeing. You can add screenshots and videos as well. If you have a repro project, you can drag and drop the .zip/etc. onto the issue editor to attach it.
      placeholder: Tell us what you see! (And how it's different from what you expected to see!)
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Describe all the steps we need to take to show the behavior that you have observed.
      placeholder: | 
        1. Create a File > New Android App (Xamarin)
        2. Add the following code: ...
        3. Run the app and observe the bug üêû
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Did you find any workaround?
      description: Did you find any workaround for this issue? This can unblock other people while waiting for this issue to be resolved or even give us a hint on how to fix this.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any (short!) relevant log output.  Longer logs can be attached as .txt files.  This is likely a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or attach a [MSBuild binlog](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022#save-a-binary-log).
      render: shell
  - type: markdown
    attributes:
      value: |
        By opening the issue you agree to follow this project's [Code of Conduct](https://dotnetfoundation.org/about/code-of-conduct).
