blank_issues_enabled: false
contact_links:
  - name: "‚öô IDE"
    url: https://developercommunity.visualstudio.com/report?entry=problem
    about: Issues with Visual Studio for Windows or Mac, or the Android Designer should be filed using the tools inside the IDE.  This allows the proper logs to be collected and forwarded to the correct team(s).
  - name: "\U0001F4A1 Feature Request"
    url: https://developercommunity.visualstudio.com
    about: Feature requests are tracked on Visual Studio Developer Community because it provides good prioritization features like voting. Filing there helps ensure new features are properly considered.
  - name: "üôã‚Äç‚ôÄÔ∏è Community Support"
    url: https://learn.microsoft.com/en-us/answers/tags/18/xamarin
    about: For issues that likely aren't bugs, Microsoft Q&A is a good place to ask for help.
